import Link from 'next/link'

export const metadata = { title: 'Terms of Service — Almost Became' }

export default function TermsPage() {
  return (
    <>
      <style>{`
        .legal-page { max-width: 720px; margin: 0 auto; padding: 80px 32px; }
        .legal-nav { display:flex; align-items:center; justify-content:space-between; padding:20px 32px; border-bottom:1px solid var(--border); position:sticky; top:0; background:var(--bg); z-index:10; }
        .legal-logo { font-family:'Playfair Display',serif; font-style:italic; color:var(--amber); font-size:18px; text-decoration:none; }
        .legal-page h1 { font-family:'Playfair Display',serif; font-size:38px; font-weight:900; margin-bottom:8px; }
        .legal-updated { font-size:13px; color:var(--muted); font-style:italic; margin-bottom:48px; }
        .legal-page h2 { font-family:'Playfair Display',serif; font-size:22px; font-weight:700; margin:40px 0 12px; color:var(--amber); }
        .legal-page p { font-size:16px; line-height:1.8; color:#c8bcaa; margin-bottom:16px; }
        .legal-page a { color:var(--amber); }
      `}</style>
      <nav className="legal-nav">
        <Link href="/" className="legal-logo">Almost Became</Link>
      </nav>
      <div className="legal-page">
        <h1>Terms of Service</h1>
        <p className="legal-updated">Last updated: {new Date().toLocaleDateString('en-CA', { month: 'long', day: 'numeric', year: 'numeric' })}</p>

        <h2>1. About Us</h2>
        <p>Almost Became ("we", "us", "our") is operated by [YOUR FULL LEGAL NAME], a sole proprietor based in Canada. By using almostbecame.com ("the Service"), you agree to these Terms.</p>

        <h2>2. Description of Service</h2>
        <p>Almost Became is an AI-powered web application that generates creative, fictional museum exhibits based on descriptions of alternative life paths. All generated content is fictional and for entertainment and personal reflection purposes only.</p>

        <h2>3. Eligibility</h2>
        <p>You must be at least 13 years of age to use this Service. By using the Service, you represent that you meet this requirement.</p>

        <h2>4. Free and Paid Tiers</h2>
        <p>The Service offers a free tier (one museum). A one-time payment of CAD $4.99 (or equivalent USD) unlocks unlimited museum creation permanently. All payments are processed securely by Stripe Inc. Prices are subject to applicable Canadian taxes. Payments are non-refundable except where required by Canadian consumer protection law.</p>

        <h2>5. User Content</h2>
        <p>You retain ownership of the descriptions you provide. By using the Service, you grant us a limited license to process your input to generate exhibits. You agree not to submit content that is illegal, defamatory, harassing, or violates the rights of others.</p>

        <h2>6. AI-Generated Content</h2>
        <p>All exhibit content is generated by Google's Gemini AI. Content is entirely fictional. We make no warranties about accuracy or suitability. Any resemblance to real persons or events is coincidental.</p>

        <h2>7. Privacy</h2>
        <p>Our collection and use of personal information is governed by our <Link href="/privacy">Privacy Policy</Link>, which complies with Canada's Personal Information Protection and Electronic Documents Act (PIPEDA).</p>

        <h2>8. Limitation of Liability</h2>
        <p>The Service is provided "as is". To the maximum extent permitted by Canadian law, we are not liable for indirect, incidental, or consequential damages. Our maximum liability shall not exceed the amount you paid for the Service.</p>

        <h2>9. Governing Law</h2>
        <p>These Terms are governed by the laws of the Province of Ontario and the federal laws of Canada applicable therein, without regard to conflict of law principles.</p>

        <h2>10. Changes</h2>
        <p>We may update these Terms at any time. Continued use of the Service after changes constitutes acceptance.</p>

        <h2>11. Contact</h2>
        <p>Questions? Email <a href="mailto:hello@almostbecame.com">hello@almostbecame.com</a></p>
      </div>
    </>
  )
}
